// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_motion_assets.sql

package db

import (
	"context"
)

const deleteProjectMotionAsset = `-- name: DeleteProjectMotionAsset :exec
DELETE FROM project_motion_assets
WHERE project_id = ? AND kind = ?
`

type DeleteProjectMotionAssetParams struct {
	ProjectID int64  `json:"project_id"`
	Kind      string `json:"kind"`
}

func (q *Queries) DeleteProjectMotionAsset(ctx context.Context, arg DeleteProjectMotionAssetParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectMotionAsset, arg.ProjectID, arg.Kind)
	return err
}

const getProjectMotionAsset = `-- name: GetProjectMotionAsset :one
SELECT project_id, kind, source_path, source_mime, preview_path, preview_mime, width, height, duration_seconds, codec, frame_rate, bitrate, has_audio, created_at, updated_at FROM project_motion_assets
WHERE project_id = ? AND kind = ?
`

type GetProjectMotionAssetParams struct {
	ProjectID int64  `json:"project_id"`
	Kind      string `json:"kind"`
}

func (q *Queries) GetProjectMotionAsset(ctx context.Context, arg GetProjectMotionAssetParams) (ProjectMotionAsset, error) {
	row := q.db.QueryRowContext(ctx, getProjectMotionAsset, arg.ProjectID, arg.Kind)
	var i ProjectMotionAsset
	err := row.Scan(
		&i.ProjectID,
		&i.Kind,
		&i.SourcePath,
		&i.SourceMime,
		&i.PreviewPath,
		&i.PreviewMime,
		&i.Width,
		&i.Height,
		&i.DurationSeconds,
		&i.Codec,
		&i.FrameRate,
		&i.Bitrate,
		&i.HasAudio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectMotionAssets = `-- name: ListProjectMotionAssets :many
SELECT project_id, kind, source_path, source_mime, preview_path, preview_mime, width, height, duration_seconds, codec, frame_rate, bitrate, has_audio, created_at, updated_at FROM project_motion_assets
WHERE project_id = ?
ORDER BY kind
`

func (q *Queries) ListProjectMotionAssets(ctx context.Context, projectID int64) ([]ProjectMotionAsset, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMotionAssets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMotionAsset{}
	for rows.Next() {
		var i ProjectMotionAsset
		if err := rows.Scan(
			&i.ProjectID,
			&i.Kind,
			&i.SourcePath,
			&i.SourceMime,
			&i.PreviewPath,
			&i.PreviewMime,
			&i.Width,
			&i.Height,
			&i.DurationSeconds,
			&i.Codec,
			&i.FrameRate,
			&i.Bitrate,
			&i.HasAudio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectMotionAsset = `-- name: UpsertProjectMotionAsset :one
INSERT INTO project_motion_assets (
    project_id,
    kind,
    source_path,
    source_mime,
    preview_path,
    preview_mime,
    width,
    height,
    duration_seconds,
    codec,
    frame_rate,
    bitrate,
    has_audio
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(project_id, kind) DO UPDATE SET
    source_path = excluded.source_path,
    source_mime = excluded.source_mime,
    preview_path = excluded.preview_path,
    preview_mime = excluded.preview_mime,
    width = excluded.width,
    height = excluded.height,
    duration_seconds = excluded.duration_seconds,
    codec = excluded.codec,
    frame_rate = excluded.frame_rate,
    bitrate = excluded.bitrate,
    has_audio = excluded.has_audio,
    updated_at = CURRENT_TIMESTAMP
RETURNING project_id, kind, source_path, source_mime, preview_path, preview_mime, width, height, duration_seconds, codec, frame_rate, bitrate, has_audio, created_at, updated_at
`

type UpsertProjectMotionAssetParams struct {
	ProjectID       int64   `json:"project_id"`
	Kind            string  `json:"kind"`
	SourcePath      string  `json:"source_path"`
	SourceMime      string  `json:"source_mime"`
	PreviewPath     string  `json:"preview_path"`
	PreviewMime     string  `json:"preview_mime"`
	Width           int64   `json:"width"`
	Height          int64   `json:"height"`
	DurationSeconds float64 `json:"duration_seconds"`
	Codec           string  `json:"codec"`
	FrameRate       float64 `json:"frame_rate"`
	Bitrate         int64   `json:"bitrate"`
	HasAudio        bool    `json:"has_audio"`
}

func (q *Queries) UpsertProjectMotionAsset(ctx context.Context, arg UpsertProjectMotionAssetParams) (ProjectMotionAsset, error) {
	row := q.db.QueryRowContext(ctx, upsertProjectMotionAsset,
		arg.ProjectID,
		arg.Kind,
		arg.SourcePath,
		arg.SourceMime,
		arg.PreviewPath,
		arg.PreviewMime,
		arg.Width,
		arg.Height,
		arg.DurationSeconds,
		arg.Codec,
		arg.FrameRate,
		arg.Bitrate,
		arg.HasAudio,
	)
	var i ProjectMotionAsset
	err := row.Scan(
		&i.ProjectID,
		&i.Kind,
		&i.SourcePath,
		&i.SourceMime,
		&i.PreviewPath,
		&i.PreviewMime,
		&i.Width,
		&i.Height,
		&i.DurationSeconds,
		&i.Codec,
		&i.FrameRate,
		&i.Bitrate,
		&i.HasAudio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
