// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: segments.sql

package db

import (
	"context"
)

const completeSegmentSet = `-- name: CompleteSegmentSet :exec
UPDATE track_segment_sets
SET file_size = ?, sample_rate = ?, sample_count = ?, channels = ?,
    init_byte_end = ?, status = 'completed'
WHERE id = ?
`

type CompleteSegmentSetParams struct {
	FileSize    int64 `json:"file_size"`
	SampleRate  int64 `json:"sample_rate"`
	SampleCount int64 `json:"sample_count"`
	Channels    int64 `json:"channels"`
	InitByteEnd int64 `json:"init_byte_end"`
	ID          int64 `json:"id"`
}

func (q *Queries) CompleteSegmentSet(ctx context.Context, arg CompleteSegmentSetParams) error {
	_, err := q.db.ExecContext(ctx, completeSegmentSet,
		arg.FileSize,
		arg.SampleRate,
		arg.SampleCount,
		arg.Channels,
		arg.InitByteEnd,
		arg.ID,
	)
	return err
}

const createSegmentFragment = `-- name: CreateSegmentFragment :exec
INSERT INTO track_segment_fragments (set_id, idx, byte_start, byte_end)
VALUES (?, ?, ?, ?)
`

type CreateSegmentFragmentParams struct {
	SetID     int64 `json:"set_id"`
	Idx       int64 `json:"idx"`
	ByteStart int64 `json:"byte_start"`
	ByteEnd   int64 `json:"byte_end"`
}

func (q *Queries) CreateSegmentFragment(ctx context.Context, arg CreateSegmentFragmentParams) error {
	_, err := q.db.ExecContext(ctx, createSegmentFragment,
		arg.SetID,
		arg.Idx,
		arg.ByteStart,
		arg.ByteEnd,
	)
	return err
}

const createSegmentSet = `-- name: CreateSegmentSet :one
INSERT INTO track_segment_sets (version_id, codec, file_path, status)
VALUES (?, ?, ?, 'pending')
ON CONFLICT(version_id, codec) DO UPDATE SET
    file_path = excluded.file_path,
    status = 'pending',
    file_size = 0,
    sample_rate = 0,
    sample_count = 0,
    channels = 0,
    init_byte_end = 0
RETURNING id, version_id, codec, file_path, file_size, sample_rate, sample_count, channels, init_byte_end, status, created_at
`

type CreateSegmentSetParams struct {
	VersionID int64  `json:"version_id"`
	Codec     string `json:"codec"`
	FilePath  string `json:"file_path"`
}

func (q *Queries) CreateSegmentSet(ctx context.Context, arg CreateSegmentSetParams) (TrackSegmentSet, error) {
	row := q.db.QueryRowContext(ctx, createSegmentSet, arg.VersionID, arg.Codec, arg.FilePath)
	var i TrackSegmentSet
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Codec,
		&i.FilePath,
		&i.FileSize,
		&i.SampleRate,
		&i.SampleCount,
		&i.Channels,
		&i.InitByteEnd,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSegmentFragments = `-- name: DeleteSegmentFragments :exec
DELETE FROM track_segment_fragments WHERE set_id = ?
`

func (q *Queries) DeleteSegmentFragments(ctx context.Context, setID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSegmentFragments, setID)
	return err
}

const failSegmentSet = `-- name: FailSegmentSet :exec
UPDATE track_segment_sets SET status = 'failed' WHERE id = ?
`

func (q *Queries) FailSegmentSet(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, failSegmentSet, id)
	return err
}

const getCompletedSegmentSet = `-- name: GetCompletedSegmentSet :one
SELECT id, version_id, codec, file_path, file_size, sample_rate, sample_count, channels, init_byte_end, status, created_at FROM track_segment_sets
WHERE version_id = ? AND codec = ? AND status = 'completed'
`

type GetCompletedSegmentSetParams struct {
	VersionID int64  `json:"version_id"`
	Codec     string `json:"codec"`
}

func (q *Queries) GetCompletedSegmentSet(ctx context.Context, arg GetCompletedSegmentSetParams) (TrackSegmentSet, error) {
	row := q.db.QueryRowContext(ctx, getCompletedSegmentSet, arg.VersionID, arg.Codec)
	var i TrackSegmentSet
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Codec,
		&i.FilePath,
		&i.FileSize,
		&i.SampleRate,
		&i.SampleCount,
		&i.Channels,
		&i.InitByteEnd,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listLosslessVersionsMissingSegments = `-- name: ListLosslessVersionsMissingSegments :many
SELECT tv.id AS version_id, tf.file_path AS source_path
FROM track_versions tv
JOIN track_files tf
    ON tf.version_id = tv.id AND tf.quality = 'source'
WHERE NOT EXISTS (
    SELECT 1 FROM track_segment_sets s
    WHERE s.version_id = tv.id
      AND s.codec = 'alac'
      AND s.status = 'completed'
)
ORDER BY tv.id
`

type ListLosslessVersionsMissingSegmentsRow struct {
	VersionID  int64  `json:"version_id"`
	SourcePath string `json:"source_path"`
}

func (q *Queries) ListLosslessVersionsMissingSegments(ctx context.Context) ([]ListLosslessVersionsMissingSegmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLosslessVersionsMissingSegments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLosslessVersionsMissingSegmentsRow{}
	for rows.Next() {
		var i ListLosslessVersionsMissingSegmentsRow
		if err := rows.Scan(&i.VersionID, &i.SourcePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegmentFragments = `-- name: ListSegmentFragments :many
SELECT idx, byte_start, byte_end FROM track_segment_fragments
WHERE set_id = ? ORDER BY idx
`

type ListSegmentFragmentsRow struct {
	Idx       int64 `json:"idx"`
	ByteStart int64 `json:"byte_start"`
	ByteEnd   int64 `json:"byte_end"`
}

func (q *Queries) ListSegmentFragments(ctx context.Context, setID int64) ([]ListSegmentFragmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSegmentFragments, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSegmentFragmentsRow{}
	for rows.Next() {
		var i ListSegmentFragmentsRow
		if err := rows.Scan(&i.Idx, &i.ByteStart, &i.ByteEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegmentSetsForVersion = `-- name: ListSegmentSetsForVersion :many
SELECT id, codec FROM track_segment_sets WHERE version_id = ?
`

type ListSegmentSetsForVersionRow struct {
	ID    int64  `json:"id"`
	Codec string `json:"codec"`
}

func (q *Queries) ListSegmentSetsForVersion(ctx context.Context, versionID int64) ([]ListSegmentSetsForVersionRow, error) {
	rows, err := q.db.QueryContext(ctx, listSegmentSetsForVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSegmentSetsForVersionRow{}
	for rows.Next() {
		var i ListSegmentSetsForVersionRow
		if err := rows.Scan(&i.ID, &i.Codec); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSegmentSetProcessing = `-- name: MarkSegmentSetProcessing :exec
UPDATE track_segment_sets SET status = 'processing' WHERE id = ?
`

func (q *Queries) MarkSegmentSetProcessing(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markSegmentSetProcessing, id)
	return err
}
